# Color Setup
# set -g allow-passthrough on
# set -ga terminal-overrides ',*:Tc'
set-option -sa terminal-overrides ",xterm*:Tc"
set -g default-terminal "screen-256color"

set -g default-terminal "tmux-256color"
set -as terminal-overrides ',xterm-256color:Tc'
set -as terminal-overrides ',xterm-256color:sitm=\E[3m'
set -as terminal-overrides ',xterm-256color:ritm=\E[23m'

# word separators for automatic word selection
setw -g word-separators ' @"=()[]'
setw -ag word-separators "'"
set -g status-interval 5

# Default terminal
#set-option -g default-terminal "tmux-256color"
#set-option -sa terminal-overrides ',xterm-termite:RGB'

# Change prefix from 'Ctrl+B' to 'Ctrl+o'
unbind C-b
set-option -g prefix C-o
bind-key C-o send-prefix

# setup mouse
set -g mouse on
setw -g alternate-screen on
set -g set-clipboard on
set -g allow-passthrough on

# set scroll speed
#bind -Tcopy-mode WheelUpPane send -N1 -X scroll-up
#bind -Tcopy-mode WheelDownPane send -N1 -X scroll-down
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if-shell -F -t = '#{pane_in_mode}' 'send-keys -t = H 1 k' 'copy-mode -e'"
bind -n WheelDownPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if-shell -F -t = '#{pane_in_mode}' 'send-keys -t = L 1 j' 'copy-mode -e'"

# split panes using | and -
bind | split-window -h -c "#{pane_current_path}"
bind _ split-window -v -c "#{pane_current_path}"
#unbind '"'
#unbind %

bind Y set-window-option synchronize-panes

bind g display-popup \
    -d "#{pane_current_path}" \
    -w 100% \
    -h 100% \
    -E "bash -c 'lazygit'"

bind h display-popup \
    -d "#{pane_current_path}" \
    -w 80% \
    -h 80% \
    -E "bash -c 'lazydocker'"

bind t display-popup \
    -d "#{pane_current_path}" \
    -w 80% \
    -h 80% \
    -E "bash"

# Style (Atom One Light)
gray_light="#FAFAFA"
gray_medium="#E5E5E6"
gray_dark="#383A42"
red_soft="#E45649"
green_soft="#50A14F"
yellow_soft="#C18401"
blue_muted="#4078F2"
cyan_soft="#0184BC"

set -g status-left-length 100
# set -g status-style "fg=${gray_dark},bg=${gray_light}"
set -g status-style "fg=default,bg=default"

# set -g status-left "#[fg=${blue_muted},bold] #S #[fg=${gray_dark},nobold]|"
set -g status-left "#[fg=${blue_muted},bold] #S #[fg=default,nobold]|"
set -g status-right "" # #[fg=${green_soft}]#(cpu) #[fg=${cyan_soft}]#(mem) "

# set -g window-status-current-format "#[fg=${blue_muted},bold] ● #[fg=${gray_dark}]#I:#W"
set -g window-status-current-format "#[fg=${blue_muted},bold] ● #[fg=default]#I:#W"
# set -g window-status-format "#[fg=${gray_dark}] #I:#W "
set -g window-status-format "#[fg=${default}] #I:#W "

# set -g message-style "fg=${gray_dark},bg=${gray_medium}"
set -g message-style "fg=default,bg=default"

set -g mode-style "fg=${gray_dark},bg=${blue_muted}"
set -g pane-border-style "fg=${gray_medium}"
set -g pane-active-border-style "fg=${blue_muted}"

set -g status-right '#(~/.tmux/git-status.sh)'

